---
name: 'Helm3'
description: "This plugin provides an interface to Helm 3"
inputs:
  mode:
    description: "Indicates the operation to perform. Recommended, but not required. Valid options are `upgrade`, `uninstall`, `lint`, and `help`."
    required: true
  chart:
    description: "The chart to use for this installation."
    required: false
  release:
    description: "The release name for helm to use."
    required: false
  namespace:
    description: "Kubernetes namespace to use for this operation."
    required: false
  values:
    description: "Chart values to use as the `--set` argument to `helm upgrade`."
    required: false
  debug:
    description: "Generate debug output within drone-helm3 and pass `--debug` to all helm commands. Use with care, since the debug output may include secrets."
    required: false
    default: "false"
  skip_kubeconfig:
    description: "Skip kubeconfig creation default `false`. If set `true` k8s api point to localhost."
    required: false
    default: "false"
  skip_tls_verify:
    description: "Connect to the Kubernetes cluster without checking for a valid TLS certificate. Not recommended in production. This is ignored if `skip_kubeconfig` is `true`."
    required: false
    default: "false"
  kubernetes_certificate:
    description: "Base64 encoded TLS certificate used by the Kubernetes cluster's certificate authority. This is ignored if `skip_kubeconfig` is `true`."
    required: false
  api_server:
    description: "API endpoint for the Kubernetes cluster. This is ignored if `skip_kubeconfig` is `true`."
    required: false
    default: "test"
  kubernetes_token:
    description: "Token for authenticating to Kubernetes. This is ignored if `skip_kubeconfig` is `true`."
    required: false
  service_account:
    description: "Service account for authenticating to Kubernetes. Default is `helm`. This is ignored if `skip_kubeconfig` is `true`."
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.mode }}
    - ${{ inputs.chart }}
    - ${{ inputs.release }}
    - ${{ inputs.namespace }}
    - ${{ inputs.values }}
    - ${{ inputs.debug }}
    - ${{ inputs.skip_kubeconfig }}
    - ${{ inputs.skip_tls_verify }}
    - ${{ inputs.kubernetes_certificate }}
    - ${{ inputs.api_server }}
    - ${{ inputs.kubernetes_token }}
    - ${{ inputs.service_account }}